print("05/06/2024")
print("Dear Tony of the future,")
print("I hope you are doing well. I am writing this letter to remind you of the goals you set for yourself in 2020.")
print("I'm also going to write down a bit of my feelings of today, so you can remember how you felt at this time.")
print("It's being a tough day, but I'm trying to keep my head up and stay positive.")
print("I hope you are doing well and that you have achieved all the goals you set for yourself.")
print("I hope you are happy and healthy, and that you are surrounded by people who love you.")
print("I hope you are still working hard and that you are proud of the person you have become.")
print("I hope you are still dreaming big and that you are still chasing your dreams.")
print("I hope you are still learning and growing, and that you are still pushing yourself to be the best you can be.")
print("I hope you are still kind and compassionate, and that you are still making a positive impact on the world.")
print("I hope you are still grateful for all the blessings in your life, and that you are still finding joy in the little things.")
print("Viva la vida.")